# Generated by Django 5.1 on 2024-09-20 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название склада')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес склада')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название товара')),
                ('article', models.CharField(default='0', max_length=50, verbose_name='Артикул')),
                ('price', models.IntegerField(blank=True, default='0', null=True, verbose_name='Цена')),
                ('barcode', models.FileField(blank=True, null=True, upload_to='barcode/%Y/%m/%d/', verbose_name='Баркод')),
                ('description', models.TextField(default='-', verbose_name='Описание')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_products/%Y/%m/%d/', verbose_name='Изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ManyToManyField(blank=True, null=True, to='appWarehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
    ]
