# Generated by Django 5.1 on 2024-09-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWarehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(default='0', max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.FileField(blank=True, null=True, upload_to='barcode/', verbose_name='Баркод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ManyToManyField(to='appWarehouse.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес склада'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название склада'),
        ),
    ]
