# Generated by Django 5.1 on 2024-09-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWarehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWarehouse.product')),
            ],
        ),
    ]
