# Generated by Django 5.1 on 2024-09-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWarehouse', '0002_alter_product_article_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ManyToManyField(blank=True, null=True, to='appWarehouse.warehouse', verbose_name='Склад'),
        ),
    ]
