# Generated by Django 5.1 on 2024-09-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWarehouse', '0002_countrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image_products/noimage.png', null=True, upload_to='image_products/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
