# Generated by Django 5.1 on 2024-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWarehouse', '0003_alter_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_products/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.FileField(blank=True, null=True, upload_to='barcode/%Y/%m/%d/', verbose_name='Баркод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='-', verbose_name='Описание'),
        ),
    ]
