# Generated by Django 5.1 on 2024-09-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appNews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='preview',
        ),
    ]
