# Generated by Django 5.1 on 2024-09-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNews', '0003_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=255, verbose_name='Слаг'),
        ),
    ]
