# Generated by Django 5.1 on 2024-09-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appNews', '0004_alter_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
